ARG RUBY_VERSION=3.2.7
FROM ruby:${RUBY_VERSION}

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential libpq-dev postgresql-client git curl && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /rails

ENV BUNDLE_PATH=/bundle \
    BUNDLE_BIN=/bundle/bin \
    GEM_HOME=/bundle
ENV PATH="${BUNDLE_BIN}:${PATH}"

EXPOSE 3000
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
