require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/weight_entries", type: :request do
  let(:user) { create(:user) }
  before { sign_in user }

  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      WeightEntry.create! valid_attributes
      get weight_entries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      weight_entry = WeightEntry.create! valid_attributes
      get weight_entry_url(weight_entry)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_weight_entry_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      weight_entry = WeightEntry.create! valid_attributes
      get edit_weight_entry_url(weight_entry)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new WeightEntry" do
        expect {
          post weight_entries_url, params: { weight_entry: valid_attributes }
        }.to change(WeightEntry, :count).by(1)
      end

      it "redirects to the created weight_entry" do
        post weight_entries_url, params: { weight_entry: valid_attributes }
        expect(response).to redirect_to(weight_entry_url(WeightEntry.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new WeightEntry" do
        expect {
          post weight_entries_url, params: { weight_entry: invalid_attributes }
        }.to change(WeightEntry, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post weight_entries_url, params: { weight_entry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested weight_entry" do
        weight_entry = WeightEntry.create! valid_attributes
        patch weight_entry_url(weight_entry), params: { weight_entry: new_attributes }
        weight_entry.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the weight_entry" do
        weight_entry = WeightEntry.create! valid_attributes
        patch weight_entry_url(weight_entry), params: { weight_entry: new_attributes }
        weight_entry.reload
        expect(response).to redirect_to(weight_entry_url(weight_entry))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        weight_entry = WeightEntry.create! valid_attributes
        patch weight_entry_url(weight_entry), params: { weight_entry: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested weight_entry" do
      weight_entry = WeightEntry.create! valid_attributes
      expect {
        delete weight_entry_url(weight_entry)
      }.to change(WeightEntry, :count).by(-1)
    end

    it "redirects to the weight_entries list" do
      weight_entry = WeightEntry.create! valid_attributes
      delete weight_entry_url(weight_entry)
      expect(response).to redirect_to(weight_entries_url)
    end
  end
end
